<?php

/**
 * Implementation of hook_init().
 */
function my_module_init() {
  if (arg(0) == 'cart') {   // ie. cart only
	  drupal_add_css(drupal_get_path('module', 'my_module') .'/css/my_module.css');
  } else {
    drupal_set_message('You clicked on a page');
  }
}
/**
 * Implementation of hook_node_insert().
 */
function my_module_node_insert($nodeid) {
	if ($nodeid->type == 'article') {
	  $nodeid->status = 0;
	  $nodeid->sticky = 1;
	  drupal_set_message('<pre>' . print_r($nodeid, TRUE) . '</pre>');
	}
}
/**
 *  My function that does stuff.
 */
function my_module_doing_stuff($nodeid) {
  // $my_node = node_load($nodeid);
  // then do more stuff
  drupal_set_message($nodeid);
}

